version: "3.9"

services:
  service1:
    build: .
    container_name: service1
    command: uvicorn service_1.main:app --host 0.0.0.0 --port 8001
    environment:
      - SERVICE_NAME=Service 1
    ports:
      - "8001:8001"

  service2:
    build: .
    container_name: service2
    command: uvicorn service_2.main:app --host 0.0.0.0 --port 8002
    environment:
      - SERVICE_NAME=Service 2
    ports:
      - "8002:8002"

  service3:
    build: .
    container_name: service3
    command: uvicorn service_1.main:app --host 0.0.0.0 --port 8003
    environment:
      - SERVICE_NAME=Service 3
    ports:
      - "8003:8003"

  load_balancer:
    build: .
    container_name: load_balancer
    depends_on:
      - service1
      - service2
      - service3
    command: uvicorn load_balancer.main:app --host 0.0.0.0 --port 8000
    environment:
      - PORT=8000
      - LB_ALGORITHM=least_connections
      - BACKEND_SERVICES=["http://service1:8001","http://service2:8002","http://service3:8003"]
    ports:
      - "8000:8000"